export const colors = {
  teal: {
    primary: '#1ABC9C',
    mid: '#66CCCC',
    light: '#73DACE',
    pale: '#AFF4C6',
    deep: '#005E5E',
    midnight: '#013F3F',
  },
  neutral: {
    black: '#000000',
    nearBlack: '#2F2F2F',
    darkUi: '#151719',
    darkText: '#1E1E1E',
    slate: '#434A54',
    navy: '#1E2A38',
    charcoal: '#34495E',
    grayText: '#757575',
    grayBorder: '#E6E6E6',
    grayLight: '#F8F8F8',
    grayMid: '#D7D7D7',
    silver: '#BDC3C7',
    offWhite: '#FDFDFD',
    white: '#FFFFFF',
  },
  accent: {
    orange: '#FFA66B',
    yellow: '#FFD76B',
    purple: '#693E71',
    blue: '#AEDFF7',
    sky: '#E6F1F5',
  },
  semantic: {
    navBg: 'var(--color-nav-bg)',
    navText: 'var(--color-nav-text)',
    navActiveBg: 'var(--color-nav-active-bg)',
    navActiveText: 'var(--color-nav-active-text)',
    heroBg: 'var(--color-hero-bg)',
    cardBg: 'var(--color-card-bg)',
    subscribeBg: 'var(--color-subscribe-bg)',
    footerBg: 'var(--color-footer-bg)',
    buttonPrimaryBg: 'var(--color-button-primary-bg)',
    buttonPrimaryText: 'var(--color-button-primary-text)',
    textHeading: 'var(--color-text-heading)',
    textBody: 'var(--color-text-body)',
    textMuted: 'var(--color-text-muted)',
    textOnDark: 'var(--color-text-on-dark)',
  },
} as const

