/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    profiles: Profile;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    brand: Brand;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    brand: BrandSelect<false> | BrandSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  layout: (
    | HeroBlock
    | MissionVisionValuesBlock
    | LeadershipBlock
    | MembershipProgramsBlock
    | DirectoryCategoriesBlock
    | MetricsBlock
    | FeatureGridBlock
    | EventPreviewBlock
    | ResourcePreviewBlock
    | NewsPreviewBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  primaryCTA: {
    type?: ('reference' | 'custom' | 'archive') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    archive?: 'posts' | null;
    /**
     * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
     */
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
  };
  secondaryCTA: {
    type?: ('reference' | 'custom' | 'archive') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    archive?: 'posts' | null;
    /**
     * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
     */
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
  };
  backgroundImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  /**
   * Use an uploaded video or link to an external video.
   */
  videoSource?: ('upload' | 'url') | null;
  /**
   * Paste a YouTube, Vimeo, or direct video URL.
   */
  videoUrl?: string | null;
  /**
   * Dropdown select for uploaded video assets from Media.
   */
  videoAsset?: (string | null) | Media;
  /**
   * Substack post GUID for sync deduplication. Set by sync-substack script.
   */
  substackId?: string | null;
  /**
   * Original Substack post URL. Set by Substack sync.
   */
  substackURL?: string | null;
  /**
   * Medium post GUID for sync deduplication. Set by sync-medium script.
   */
  mediumId?: string | null;
  /**
   * Original Medium post URL. Set by Medium sync.
   */
  mediumURL?: string | null;
  /**
   * Paragraph post ID for sync deduplication. Set by sync-paragraph script.
   */
  paragraphId?: string | null;
  /**
   * Original Paragraph post URL. Set by Paragraph sync.
   */
  paragraphURL?: string | null;
  /**
   * Cross-post workflow status for imported external posts.
   */
  crosspostReviewStatus?: ('in_review' | 'approved' | 'rejected' | 'auto_published') | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Auto-detected from uploaded file MIME type when possible, but you can set it manually.
   */
  mediaType: 'image' | 'video' | 'audio';
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionVisionValuesBlock".
 */
export interface MissionVisionValuesBlock {
  mission: string;
  vision: string;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'missionVisionValuesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBlock".
 */
export interface LeadershipBlock {
  title: string;
  intro?: string | null;
  selectedLeadership?: (string | Profile)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadershipBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  photo?: (string | null) | Media;
  title?: string | null;
  company?: string | null;
  component?: ('pros' | 'fresh' | 'education' | 'facets' | 'leadership') | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  linkedIn?: string | null;
  website?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipProgramsBlock".
 */
export interface MembershipProgramsBlock {
  title: string;
  intro?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        icon?: (string | null) | Media;
        cta: {
          type?: ('reference' | 'custom' | 'archive') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          archive?: 'posts' | null;
          /**
           * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
           */
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'membershipProgramsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectoryCategoriesBlock".
 */
export interface DirectoryCategoriesBlock {
  creators: {
    title: string;
    description?: string | null;
    image?: (string | null) | Media;
    cta: {
      type?: ('reference' | 'custom' | 'archive') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      archive?: 'posts' | null;
      /**
       * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
       */
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
    };
  };
  foundersInvestors: {
    title: string;
    description?: string | null;
    image?: (string | null) | Media;
    cta: {
      type?: ('reference' | 'custom' | 'archive') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      archive?: 'posts' | null;
      /**
       * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
       */
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
    };
  };
  nonprofits: {
    title: string;
    description?: string | null;
    image?: (string | null) | Media;
    cta: {
      type?: ('reference' | 'custom' | 'archive') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      archive?: 'posts' | null;
      /**
       * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
       */
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
    };
  };
  businesses: {
    title: string;
    description?: string | null;
    image?: (string | null) | Media;
    cta: {
      type?: ('reference' | 'custom' | 'archive') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      archive?: 'posts' | null;
      /**
       * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
       */
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
    };
  };
  speakers: {
    title: string;
    description?: string | null;
    image?: (string | null) | Media;
    cta: {
      type?: ('reference' | 'custom' | 'archive') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      archive?: 'posts' | null;
      /**
       * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
       */
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'directoryCategoriesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  metrics?:
    | {
        stat: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metricsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  title: string;
  description?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventPreviewBlock".
 */
export interface EventPreviewBlock {
  title?: string | null;
  events?: (string | Post)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventPreviewBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourcePreviewBlock".
 */
export interface ResourcePreviewBlock {
  title?: string | null;
  resources?: (string | Post)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'resourcePreviewBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsPreviewBlock".
 */
export interface NewsPreviewBlock {
  title?: string | null;
  news?: (string | Post)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsPreviewBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        heroBlock?: T | HeroBlockSelect<T>;
        missionVisionValuesBlock?: T | MissionVisionValuesBlockSelect<T>;
        leadershipBlock?: T | LeadershipBlockSelect<T>;
        membershipProgramsBlock?: T | MembershipProgramsBlockSelect<T>;
        directoryCategoriesBlock?: T | DirectoryCategoriesBlockSelect<T>;
        metricsBlock?: T | MetricsBlockSelect<T>;
        featureGridBlock?: T | FeatureGridBlockSelect<T>;
        eventPreviewBlock?: T | EventPreviewBlockSelect<T>;
        resourcePreviewBlock?: T | ResourcePreviewBlockSelect<T>;
        newsPreviewBlock?: T | NewsPreviewBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  primaryCTA?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        archive?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  secondaryCTA?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        archive?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionVisionValuesBlock_select".
 */
export interface MissionVisionValuesBlockSelect<T extends boolean = true> {
  mission?: T;
  vision?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBlock_select".
 */
export interface LeadershipBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  selectedLeadership?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipProgramsBlock_select".
 */
export interface MembershipProgramsBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectoryCategoriesBlock_select".
 */
export interface DirectoryCategoriesBlockSelect<T extends boolean = true> {
  creators?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  foundersInvestors?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  nonprofits?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  businesses?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  speakers?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock_select".
 */
export interface MetricsBlockSelect<T extends boolean = true> {
  metrics?:
    | T
    | {
        stat?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventPreviewBlock_select".
 */
export interface EventPreviewBlockSelect<T extends boolean = true> {
  title?: T;
  events?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourcePreviewBlock_select".
 */
export interface ResourcePreviewBlockSelect<T extends boolean = true> {
  title?: T;
  resources?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsPreviewBlock_select".
 */
export interface NewsPreviewBlockSelect<T extends boolean = true> {
  title?: T;
  news?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  videoSource?: T;
  videoUrl?: T;
  videoAsset?: T;
  substackId?: T;
  substackURL?: T;
  mediumId?: T;
  mediumURL?: T;
  paragraphId?: T;
  paragraphURL?: T;
  crosspostReviewStatus?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  photo?: T;
  title?: T;
  company?: T;
  component?: T;
  bio?: T;
  linkedIn?: T;
  website?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  mediaType?: T;
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'archive') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          archive?: 'posts' | null;
          /**
           * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  subscribeSection?: {
    slogan?: string | null;
    showSubscribe?: boolean | null;
  };
  linkGroups?:
    | {
        header?: string | null;
        links: {
          link: {
            type?: ('reference' | 'custom' | 'archive') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            archive?: 'posts' | null;
            /**
             * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
             */
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        /**
         * URL (e.g. https://github.com/you) or email (e.g. you@domain.com — mailto: is added automatically)
         */
        url: string;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright text shown at bottom of footer.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: string;
  fonts: {
    title: string;
    copy: string;
  };
  colors: {
    light: {
      background: string;
      foreground: string;
      card: string;
      cardForeground: string;
      popover: string;
      popoverForeground: string;
      primary: string;
      primaryForeground: string;
      secondary: string;
      secondaryForeground: string;
      muted: string;
      mutedForeground: string;
      accent: string;
      accentForeground: string;
      destructive: string;
      destructiveForeground: string;
      border: string;
      input: string;
      ring: string;
      success: string;
      warning: string;
      error: string;
    };
    dark: {
      background: string;
      foreground: string;
      card: string;
      cardForeground: string;
      popover: string;
      popoverForeground: string;
      primary: string;
      primaryForeground: string;
      secondary: string;
      secondaryForeground: string;
      muted: string;
      mutedForeground: string;
      accent: string;
      accentForeground: string;
      destructive: string;
      destructiveForeground: string;
      border: string;
      input: string;
      ring: string;
      success: string;
      warning: string;
      error: string;
    };
  };
  /**
   * CSS border radius token. Example: 0.5rem
   */
  radius: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              archive?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  subscribeSection?:
    | T
    | {
        slogan?: T;
        showSubscribe?: T;
      };
  linkGroups?:
    | T
    | {
        header?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    archive?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  fonts?:
    | T
    | {
        title?: T;
        copy?: T;
      };
  colors?:
    | T
    | {
        light?:
          | T
          | {
              background?: T;
              foreground?: T;
              card?: T;
              cardForeground?: T;
              popover?: T;
              popoverForeground?: T;
              primary?: T;
              primaryForeground?: T;
              secondary?: T;
              secondaryForeground?: T;
              muted?: T;
              mutedForeground?: T;
              accent?: T;
              accentForeground?: T;
              destructive?: T;
              destructiveForeground?: T;
              border?: T;
              input?: T;
              ring?: T;
              success?: T;
              warning?: T;
              error?: T;
            };
        dark?:
          | T
          | {
              background?: T;
              foreground?: T;
              card?: T;
              cardForeground?: T;
              popover?: T;
              popoverForeground?: T;
              primary?: T;
              primaryForeground?: T;
              secondary?: T;
              secondaryForeground?: T;
              muted?: T;
              mutedForeground?: T;
              accent?: T;
              accentForeground?: T;
              destructive?: T;
              destructiveForeground?: T;
              border?: T;
              input?: T;
              ring?: T;
              success?: T;
              warning?: T;
              error?: T;
            };
      };
  radius?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Choose which kind of media to insert into this block.
   */
  mediaType: 'image' | 'video' | 'audio';
  /**
   * Choose how this media block is laid out on the page.
   */
  displayStyle?: ('default' | 'fullWidthTransition' | 'heroOverlay') | null;
  /**
   * For hero overlay or book image with links: High Impact increases height and font size.
   */
  overlayVariant?: ('standard' | 'highImpact') | null;
  /**
   * Overlay opacity (0–100). Darkens the image so overlay links are readable.
   */
  overlayOpacity?: number | null;
  /**
   * Links overlay the center of the image (e.g. O'Reilly, Amazon).
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'archive') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          archive?: 'posts' | null;
          /**
           * URL (e.g. https://example.com) or email (e.g. you@domain.com — mailto: is added automatically)
           */
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'accent' | 'light' | 'inactive' | 'filter' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional rich text above overlay links when this image is followed by a block with links (e.g. 'Buy').
   */
  overlayRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Choose an existing video asset or create a new one once.
   */
  video?: (string | null) | Media;
  /**
   * Pick a local video asset or paste a video URL.
   */
  videoSource?: ('upload' | 'url') | null;
  /**
   * Supports YouTube links and direct .mp4/.webm URLs.
   */
  videoUrl?: string | null;
  /**
   * Optional poster image for video.
   */
  thumbnail?: (string | null) | Media;
  audio?: (string | null) | Media;
  /**
   * Legacy field for existing content. Use Image/Video/Audio above for new content.
   */
  media?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}